server:
  port: 8080
spring:
  application:
    name: ignite-vehicle-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  main:
    allow-circular-references: true
logging:
  config: classpath:log4j2.xml